name: .NET Core

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
#      run: dotnet build --configuration Release InfoValutar\InfoValutarDOS\InfoValutarDOS.csproj
#      run: dotnet publish  -r win10-x64 -p:PublishSingleFile=true --self-contained InfoValutar\InfoValutarDOS\InfoValutarDOS.csproj
      run: dotnet publish InfoValutar/InfoValutarDOS/InfoValutarDOS.csproj -r win10-x64 -p:PublishSingleFile=true --self-contained 
    - name: run tests
      run: dotnet test --filter "External=0" InfoValutar/InfovalutarTest/InfovalutarTest.csproj 
    - name: TOC Generator
      uses: technote-space/toc-generator@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        TARGET_PATHS: 'README.md'
      

